### ISSUE TITLE
about datasets release

### ISSUE THREAD

**Issue by syspider** [baaivision/EVE#1]
Hi, 
Thanks for your excellent work about exploring the implement of VLMs! Will the training datasets be released together with codes and model weights? It would be very great and helpful for VLMs' open-source community. Many thanks~

**Comment by Paranioar** [comment]
> Hi, Thanks for your excellent work about exploring the implement of VLMs! Will the training datasets be released together with codes and model weights? It would be very great and helpful for VLMs' open-source community. Many thanks~

We currently release the evaluation code and models, and are sorting out the training code. As for the open source of the pre-training data, we have no specific plans.
