### ISSUE TITLE
Experimental setting of EVE w/ stage1 in Table 5

### ISSUE THREAD

**Issue by ttccxx** [baaivision/EVE#12]
Hi, thanks for your great work!

I'm curious about the specific experimental setting of EVE w/ stage1 in Table 5, shown in the figure below.\
![image](https://github.com/user-attachments/assets/0972be2d-2d9b-4379-8007-fb84b2984a70)

Would you please provide the amount of training data in each stage of this model? Appreciate your time and help in advance!

**Comment by Paranioar** [comment]
> Hi, thanks for your great work!
> 
> I'm curious about the specific experimental setting of EVE w/ stage1 in Table 5, shown in the figure below. ![image](https://private-user-images.githubusercontent.com/42903435/359744969-0972be2d-2d9b-4379-8007-fb84b2984a70.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ0NzYxMjcsIm5iZiI6MTcyNDQ3NTgyNywicGF0aCI6Ii80MjkwMzQzNS8zNTk3NDQ5NjktMDk3MmJlMmQtMmQ5Yi00Mzc5LTgwMDctZmI4NGIyOTg0YTcwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI0VDA1MDM0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJkMWE3NDJiZjg5MzVjYmZmZDc4MGM2ODIwYjdjNDc3ZWMzMzU3YzRmNTFkNmJhOWY0YzQzNTNlYTc3YTRkNzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.x7MWzfYcMESvmUA99YlZj9ZXV-KoatXG8y4oLv7qCeo)
> 
> Would you please provide the amount of training data in each stage of this model? Appreciate your time and help in advance!

We use 8M of 33M pretraining data to train PEL and PAL solely, and then directly utilize LLava-mix-665K to finetune all modules. We also tried 16/33M and didn't see much difference during this setting.
