### ISSUE TITLE
Pre-Alignment Stage 1 Training JSON Format

### ISSUE THREAD

**Issue by nishitanand** [baaivision/EVE#13]
Hi, thank you for your work. I wanted to ask that for Pre-Alignment Stage 1 Training, what is the JSON Format to be used. It would be helpful if you could give a sample of the json.

**Comment by Paranioar** [comment]
> Hi, thank you for your work. I wanted to ask that for Pre-Alignment Stage 1 Training, what is the JSON Format to be used. It would be helpful if you could give a sample of the json.

Here is some examples of JSON file:

[
{"id": "3879379004556", "image": "LAION-Dedump/images/000339/3879379004556.png", "conversations": [{"from": "human", "value": "\<image>"},  {"from": "gpt", "value": "In the center, xxxxxxx."}]}, 
{"id": "1160817002721", "image": "LAION-Dedump/images/000339/1160817002721.png", "conversations": [{"from": "human", "value": "\<image>"}, {"from": "gpt", "value": "The slide is titled xxxxxxx."}]}, 
{"id": "1149667002714", "image": "LAION-Dedump/images/000339/1149667002714.png", "conversations": [{"from": "human", "value": "\<image>"}, {"from": "gpt", "value": "The photo depicts xxxxxxx."}]},
...
]
