### ISSUE TITLE
Question about the generation of EVE-cap33M.

### ISSUE THREAD

**Issue by HYZ17** [baaivision/EVE#14]
Hello, I would like to know more details about the generation of the image description in EVE-cap33M. For example, what prompt do you use to generate the description? And what about the hyper-parameters for generation? Thank you.

**Comment by Paranioar** [comment]
> Hello, I would like to know more details about the generation of the image description in EVE-cap33M. For example, what prompt do you use to generate the description? And what about the hyper-parameters for generation? Thank you.

I'm sorry for not getting back to you sooner. We actually collected some publicly available image-text data sets annotated from GPT-4v and finetuned the network specifically for annotation.
