### ISSUE TITLE
Experiment setting of "From scratch" in Figure 6

### ISSUE THREAD

**Issue by ShacklesLay** [baaivision/EVE#15]
Hi, thanks for your great work.

I'm curious about the specific experimental setting of "From scratch" in Figure 6, shown in the figure below, but I couldn’t find the details in the paper.
![image](https://github.com/user-attachments/assets/3b3c1802-75fc-4e65-bff7-15270bb178d3)

Could you please provide more information on this? Thank you for your time and assistance!

**Comment by Paranioar** [comment]
"From scratch" means that we train LLM from scratch without any initialization. We will polish the related section for better classification.
