### ISSUE TITLE
Questions on Experimental Setup and Model Performance Variations in Figure 7

### ISSUE THREAD

**Issue by ShacklesLay** [baaivision/EVE#16]
Hello, thanks for your insightful work again, I have more questions to ask. XD

I have some questions regarding the experimental graph depicted:
![image](https://github.com/user-attachments/assets/daa833d1-fb4a-4a05-a802-4874255c6377)

1. Does the x-axis represent the amount of data used in the second stage? Does the data amount used in the first stage change as the data amount in the second stage varies?
2. Recent works have mentioned the benefits of unfreezing the vision encoder during the SFT stage to enhance model performance. Why consider unfreezing the vision encoder in stage 2 rather than stage 3?
3. Is Llava's projector trained during stage 2?
4. The encoder-based model in the (ALL)-(ALL) configuration seems closest to EVE. Why do their metrics show opposite trends as the data volume increases?

Thank you for your time and assistance.

**Comment by Paranioar** [comment]
1. Yes, it means the second stage. We emphasize that x-axis denotes the training step with an increased data scale, not the different data scales for the multiple training processes. We empirically discover that 8M is saturated, and the difference between 16M is not obvious in stage 1. My intuition is that a fixed 8M training is enough, but make sure the data sources are consistent in both stages.
2. EVE needs to train the vision perception, i.e. patch embedding layer from scratch, so we train it over the entire training process. For the vision encoder (CLIP), we found that unfreezing it in all stages leads to a model collapse of VE, which does not bring any improvements but introduces more computational costs.
3. Yes, the projector layer is trained across all configurations.
4. As mentioned in the related section, please check them in our paper.
