### ISSUE TITLE
question about train

### ISSUE THREAD

**Issue by QwYko-AHU** [baaivision/EVE#2]
hi，
Thanks for your excellent work.I noticed that the code and scripts related to train seemed not to be provided in the documents you provided. I would like to know if you plan to disclose the documents related to train? If so, when will it be made public?

**Comment by Paranioar** [comment]
> hi， Thanks for your excellent work.I noticed that the code and scripts related to train seemed not to be provided in the documents you provided. I would like to know if you plan to disclose the documents related to train? If so, when will it be made public?

Tomorrow.
