### ISSUE TITLE
Fine-tuning Stage

### ISSUE THREAD

**Issue by QwYko-AHU** [baaivision/EVE#3]
hi，
Thanks for your excellent work.I want to know whether the weight file used in the third Stage of training, Supervised Fine-tuning Stage, is EVE_7B_Pretrain or some other checkpoint file.This CKPT_PATH is found on line 31 of the scripts/eve/eve7b_finetune.sh export CKPT_PATH=checkpoints/ EVE-7B-PRTR1-672-MSE。

**Comment by Paranioar** [comment]
We just renamed the 'EVE-7B-PRTR1-672-MSE' file as 'EVE-7B-Pretrain-v1.0'. 
We update the script to clear up the misunderstanding just now.
