### ISSUE TITLE
Image Generation Capability

### ISSUE THREAD

**Issue by ZeroAGI** [baaivision/EVE#6]
Hi, 

Nice Work!

I am wondering have you ever test the Image Generation Capability of EVE? Do you have any generation examples?

Thanks

**Comment by Paranioar** [comment]
> Hi,
> 
> Nice Work!
> 
> I am wondering have you ever test the Image Generation Capability of EVE? Do you have any generation examples?
> 
> Thanks

We haven't tested EVE's generation capability. We only use CLIP features to supervise the outputs of the vision part. Indeed, there are some points worth looking into.
