### ISSUE TITLE
Pre-align checkpoint

### ISSUE THREAD

**Issue by PhoenixZ810** [baaivision/EVE#7]
Thanks for your excellent work! :heart_eyes:

Since the checkpoints for pretraining and SFT have been released, I was wondering if you could also release the pre-align model for broader use. It would be incredibly kind of you to make the pre-align checkpoint available :smiley: .

Have a nice day!

**Comment by Paranioar** [comment]
> Thanks for your excellent work! 😍
> 
> Since the checkpoints for pretraining and SFT have been released, I was wondering if you could also release the pre-align model for broader use. It would be incredibly kind of you to make the pre-align checkpoint available 😃 .
> 
> Have a nice day!

We currently do not have a specific release plan. It is advisable to train Stage 1 using some data from the same domain as Stage 2, as this benefits the training process in Stage 2. We recommend using your own data to pre-align PEL for a seamless transition to Stage 2.
